services:

  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:dev
    env_file:
      - ../.env
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - selenium-hub
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "bash", "-c", "bash /app/docker/entrypoints/development_entrypoint.sh" ]
    networks:
      - uvlhub_network

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

  nginx:
    container_name: nginx_web_server_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - uvlhub_network

  redis:
    image: "redis:latest"
    container_name: redis_container
    networks:
      - uvlhub_network

  worker:
    container_name: rq_worker_container
    env_file:
      - ../.env
    depends_on:
      - redis
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.worker
    volumes:
      - ../app/:/app/app
      - ../core/:/app/core
      - ../uploads/:/app/uploads
    networks:
      - uvlhub_network

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - uvlhub_network

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-chrome
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
    depends_on:
      - selenium-hub
    networks:
      - uvlhub_network

  firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-firefox
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
    depends_on:
      - selenium-hub
    networks:
      - uvlhub_network

volumes:
  db_data:

networks:
  uvlhub_network:
    driver: bridge
    name: uvlhub_network
  docker_uvlhub_network:
    driver: bridge
    name: docker_uvlhub_network
